---

- name: Make sure UFW is present
  ansible.builtin.package:
    name: ufw
    state: present

- name: Make sure UFW is enabled and started
  ansible.builtin.systemd:
    name: ufw.service
    state: started
    enabled: true
    masked: false

...
